### ISSUE TITLE
Missing fclose

### ISSUE THREAD

**Issue by maddin200** [leesavide/abcmidi#1]
stresspat.c line 541 missing fclose(inhandle);

**Comment by leesavide** [comment]
From [README.md](https://github.com/leesavide/abcmidi/blob/6e9339fe29615cab21ac9a7bf5595b03ca82f195/README.md#bug-reports):

>Please report any bugs you find in abc2midi, midi2abc, midicopy, or 
abcmatch, abc2abc to seymour.shlien@crc.ca (preferably with 
an example so that I can replicate the problem). Better still, send 
me the repaired source files which fix the problem! If you add your
own features to the code that other people might want to use then let 
me know.  I may or may not want to add them to the official version.
So far I have been maintaining the code, but I don't guarantee anything.

I'm simply maintaining the source code. :+1:
